defaults: &defaults
  aws:
    access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
    secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
    bucket_name: CHANGEME

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
